spring.application.name=14.7_OBPM_Setup

# Oracle Database Config
#dont use#spring.datasource.url=jdbc:oracle:thin:@10.101.7.220:1521/cbspdb.ad.tbank.bt
spring.datasource.url=jdbc:oracle:thin:@//10.101.9.227:1521/cbspdb.ad.tbank.bt
spring.datasource.username=FCUBSPROD
spring.datasource.password=fccT6#2o1o
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=false
#spring.datasource.initialization-mode=never
#server.error.include-stacktrace=never
#server.error.include-message=always

spring.datasource.hikari.data-source-properties.oracle.jdbc.fanEnabled=false
spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.data-source-properties.oracle.net.disableOob=true
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048

#weblogic deploy
#spring.datasource.jndi-name=jdbc/fcjdevDS_Loan
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.datasource.initialize=false
#spring.jpa.generate-ddl=false

# Hikari Pool
#spring.datasource.hikari.minimum-idle=10
#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.max-lifetime=1800000