apiVersion: apps/v1
kind: Deployment

metadata:
  name: loan-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: loan-api

  template:
    metadata:
      labels:
        app: loan-api

    spec:
      containers:
        - name: loan-api
          image: loan-api:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8080